import { OptionProps } from "@/types";

export const manufacturers = [
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "GMC",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Maserati",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "MINI",
    "Mitsubishi",
    "Nissan",
    "Porsche",
    "Ram",
    "Rolls-Royce",
    "Subaru",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
  ];
  
  export const yearsOfProduction:OptionProps[]= [
    { type:'year',title: "Year", value: "" },
    { type:'year',title: "2015", value: "2015" },
    { type:'year',title: "2016", value: "2016" },
    { type:'year',title: "2017", value: "2017" },
    { type:'year',title: "2018", value: "2018" },
    { type:'year',title: "2019", value: "2019" },
    { type:'year',title: "2020", value: "2020" },
    {type:'year', title: "2021", value: "2021" },
    { type:'year',title: "2022", value: "2022" },
    { type:'year',title: "2023", value: "2023" },
  ];
  
  export const fuels:OptionProps[] = [
    {type:'fuel',
      title: "Fuel",
      value: "",
    },
    {type:'fuel',
      title: "Gas",
      value: "Gas",
    },
    {type:'fuel',
      title: "Electricity",
      value: "Electricity",
    },
  ];
   

  export const testimonial=[
    { name: "Nakul Bhardwaj",
      image:"/test1.jpeg",
      twitter:"@Nakooll",
      text:"I sold my Swift for a very good price and got the money deposited within 30 minutes; the process was simple.",
    },
    { name: "Stephan",
      image:"/test2.jpeg",
      twitter:"@steev",
      text:"It's very easy to sell your car in a single visit at a high price, which will leave you happy and satisfied. Same-day bank account transfers make it very reliable.",
    },
    { name: "Sam Eepan",
      twitter:"@sam",
      image:"/test3.jpeg",
      text:"Simply awesome! From the car inspection to the quick online payment transfer, every step was fast, well-planned, and excellently executed.",
    },
    { name: "Annie",
      twitter:"@ann_ie",
      image:"/test4.jpeg",
      text:"With CarHub, not only have I got the best value of my car, but also got offered a free RC transfer. Kudos!",
    },
    { name: "Emil Raghav",
      twitter:"@emill",
      image:"/test5.jpeg",
      text:"Do you feel like selling your car is a long and painful process? I just sold my car to CARS24 in a single visit. Got a great price for my car and sold it in a hassle-free way.",
    },
    { name: "Vidhya Mandal",
      twitter:"@vidhyaa",
      image:"/test6.jpeg",
      text:"Sold my car to CarHub. It was a very good and hassle-free experience. Thank you, and please take good care of it.",
    },
    { name: "Jein ",
      twitter:"@jein_mia",
      image:"/test7.jpeg",
      text:"CarHub is highly professional, and I had an amazing experience! I sold my car in just one day and received a very good value. Keep up the excellent work!",
    },
    { name: "Riya Martin",
      twitter:"@riya_m",
      image:"/test8.jpeg",
      text:"We sold our Karnataka-registered car in Mumbai and they handled everything seamlessly. We received an excellent price, and the payment was in our account within the same week.",
    },
    { name: "Juhi",
      twitter:"@juhi",
      image:"/test9.jpeg",
      text:"CarHub made selling my Verna a breeze. The team handled everything with clear communication, and ensured a seamless process, including inspection, pickup, and instant payment.",
    }
  ]
  export const footerLinks = [
    {
      title: "About",
      links: [
        { title: "How it works", url: "/howitworks" },
     
        { title: "Security", url: "/Security" },
       
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Testimonials", url: "/Testimonial" },
        { title: "Blog", url: "/blog" },
       
      ],
    },
    {
      title: "Socials",
      links: [
        
        { title: "Instagram", url: "/" },
        { title: "Twitter", url: "/" },
        { title: "Facebook", url: "/" },
      ],
    },
  ];


  export const users=[
    { name: "Nakul Bhardwaj",
      image:"/test1.jpeg",
      twitter:"@Nakooll",
      text:"I sold my Swift for a very good price and got the money deposited within 30 minutes; the process was simple.",
    },
    { name: "Stephan",
      image:"/test2.jpeg",
      twitter:"@steev",
      text:"It's very easy to sell your car in a single visit at a high price, which will leave you happy and satisfied. Same-day bank account transfers make it very reliable.",
    },
    { name: "Sam Eepan",
      twitter:"@sam",
      image:"/test3.jpeg",
      text:"Simply awesome! From the car inspection to the quick online payment transfer, every step was fast, well-planned, and excellently executed.",
    },
    { name: "Annie",
      twitter:"@ann_ie",
      image:"/test4.jpeg",
      text:"With CarHub, not only have I got the best value of my car, but also got offered a free RC transfer. Kudos!",
    },
    { name: "Emil Raghav",
      twitter:"@emill",
      image:"/test5.jpeg",
      text:"Do you feel like selling your car is a long and painful process? I just sold my car to CARS24 in a single visit. Got a great price for my car and sold it in a hassle-free way.",
    },
    { name: "Vidhya Mandal",
      twitter:"@vidhyaa",
      image:"/test6.jpeg",
      text:"Sold my car to CarHub. It was a very good and hassle-free experience. Thank you, and please take good care of it.",
    },
    { name: "Jein ",
      twitter:"@jein_mia",
      image:"/test7.jpeg",
      text:"CarHub is highly professional, and I had an amazing experience! I sold my car in just one day and received a very good value. Keep up the excellent work!",
    },
    { name: "Riya Martin",
      twitter:"@riya_m",
      image:"/test8.jpeg",
      text:"We sold our Karnataka-registered car in Mumbai and they handled everything seamlessly. We received an excellent price, and the payment was in our account within the same week.",
    },
    { name: "Juhi",
      twitter:"@juhi",
      image:"/test9.jpeg",
      text:"CarHub made selling my Verna a breeze. The team handled everything with clear communication, and ensured a seamless process, including inspection, pickup, and instant payment.",
    }
  ]